# Stage 1: build Angular
FROM node:18 AS build-stage
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build:docker

# Stage 2: serve con Nginx
FROM nginx:alpine
COPY --from=build-stage /app/dist/library-client/browser /usr/share/nginx/html

# Copia il tuo nginx.conf personalizzato
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
